// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'WEB_FIREBASE_API_KEY',
      defaultValue: 'YOUR_WEB_FIREBASE_API_KEY',
    ),
    appId: String.fromEnvironment(
      'WEB_FIREBASE_APP_ID',
      defaultValue: 'YOUR_WEB_FIREBASE_APP_ID',
    ),
    messagingSenderId: String.fromEnvironment(
      'WEB_FIREBASE_SENDER_ID',
      defaultValue: 'YOUR_WEB_FIREBASE_SENDER_ID',
    ),
    projectId: String.fromEnvironment(
      'WEB_FIREBASE_PROJECT_ID',
      defaultValue: 'YOUR_WEB_FIREBASE_PROJECT_ID',
    ),
    authDomain: String.fromEnvironment(
      'WEB_FIREBASE_AUTH_DOMAIN',
      defaultValue: 'YOUR_WEB_FIREBASE_AUTH_DOMAIN',
    ),
    storageBucket: String.fromEnvironment(
      'WEB_FIREBASE_STORAGE_BUCKET',
      defaultValue: 'YOUR_WEB_FIREBASE_STORAGE_BUCKET',
    ),
    measurementId: String.fromEnvironment(
      'WEB_FIREBASE_MEASUREMENT_ID',
      defaultValue: 'YOUR_WEB_FIREBASE_MEASUREMENT_ID',
    ),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'ANDROID_FIREBASE_API_KEY',
      defaultValue: 'YOUR_ANDROID_FIREBASE_API_KEY',
    ),
    appId: String.fromEnvironment(
      'ANDROID_FIREBASE_APP_ID',
      defaultValue: 'YOUR_ANDROID_FIREBASE_APP_ID',
    ),
    messagingSenderId: String.fromEnvironment(
      'ANDROID_FIREBASE_SENDER_ID',
      defaultValue: 'YOUR_ANDROID_FIREBASE_SENDER_ID',
    ),
    projectId: String.fromEnvironment(
      'ANDROID_FIREBASE_PROJECT_ID',
      defaultValue: 'YOUR_ANDROID_FIREBASE_PROJECT_ID',
    ),
    storageBucket: String.fromEnvironment(
      'ANDROID_FIREBASE_STORAGE_BUCKET',
      defaultValue: 'YOUR_ANDROID_FIREBASE_STORAGE_BUCKET',
    ),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'IOS_FIREBASE_API_KEY',
      defaultValue: 'YOUR_IOS_FIREBASE_API_KEY',
    ),
    appId: String.fromEnvironment(
      'IOS_FIREBASE_APP_ID',
      defaultValue: 'YOUR_IOS_FIREBASE_APP_ID',
    ),
    messagingSenderId: String.fromEnvironment(
      'IOS_FIREBASE_SENDER_ID',
      defaultValue: 'YOUR_IOS_FIREBASE_SENDER_ID',
    ),
    projectId: String.fromEnvironment(
      'IOS_FIREBASE_PROJECT_ID',
      defaultValue: 'YOUR_IOS_FIREBASE_PROJECT_ID',
    ),
    storageBucket: String.fromEnvironment(
      'IOS_FIREBASE_STORAGE_BUCKET',
      defaultValue: 'YOUR_IOS_FIREBASE_STORAGE_BUCKET',
    ),
    iosBundleId: String.fromEnvironment(
      'IOS_FIREBASE_BUNDLE_ID',
      defaultValue: 'com.example.app',
    ),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'MACOS_FIREBASE_API_KEY',
      defaultValue: 'YOUR_MACOS_FIREBASE_API_KEY',
    ),
    appId: String.fromEnvironment(
      'MACOS_FIREBASE_APP_ID',
      defaultValue: 'YOUR_MACOS_FIREBASE_APP_ID',
    ),
    messagingSenderId: String.fromEnvironment(
      'MACOS_FIREBASE_SENDER_ID',
      defaultValue: 'YOUR_MACOS_FIREBASE_SENDER_ID',
    ),
    projectId: String.fromEnvironment(
      'MACOS_FIREBASE_PROJECT_ID',
      defaultValue: 'YOUR_MACOS_FIREBASE_PROJECT_ID',
    ),
    storageBucket: String.fromEnvironment(
      'MACOS_FIREBASE_STORAGE_BUCKET',
      defaultValue: 'YOUR_MACOS_FIREBASE_STORAGE_BUCKET',
    ),
    iosBundleId: String.fromEnvironment(
      'MACOS_FIREBASE_BUNDLE_ID',
      defaultValue: 'com.example.app.macos',
    ),
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'WINDOWS_FIREBASE_API_KEY',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_API_KEY',
    ),
    appId: String.fromEnvironment(
      'WINDOWS_FIREBASE_APP_ID',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_APP_ID',
    ),
    messagingSenderId: String.fromEnvironment(
      'WINDOWS_FIREBASE_SENDER_ID',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_SENDER_ID',
    ),
    projectId: String.fromEnvironment(
      'WINDOWS_FIREBASE_PROJECT_ID',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_PROJECT_ID',
    ),
    authDomain: String.fromEnvironment(
      'WINDOWS_FIREBASE_AUTH_DOMAIN',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_AUTH_DOMAIN',
    ),
    storageBucket: String.fromEnvironment(
      'WINDOWS_FIREBASE_STORAGE_BUCKET',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_STORAGE_BUCKET',
    ),
    measurementId: String.fromEnvironment(
      'WINDOWS_FIREBASE_MEASUREMENT_ID',
      defaultValue: 'YOUR_WINDOWS_FIREBASE_MEASUREMENT_ID',
    ),
  );
}
