// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnhJvbzYCu0VxUqSG8hhf6oRITqTpRms4',
    appId: '1:111924293210:web:bc70d1d307c821a5d3f263',
    messagingSenderId: '111924293210',
    projectId: 'smartbar-4700',
    authDomain: 'smartbar-4700.firebaseapp.com',
    storageBucket: 'smartbar-4700.firebasestorage.app',
    measurementId: 'G-9EX3BPY7SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTY1AnyImqeJKzmns8_8Yh2gi0gH4pELo',
    appId: '1:111924293210:android:9d66527ee105c54fd3f263',
    messagingSenderId: '111924293210',
    projectId: 'smartbar-4700',
    storageBucket: 'smartbar-4700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_ooudAP-7AnSEoQLLTupnN_up9fnGXM',
    appId: '1:111924293210:ios:c7ed8cc55135eef8d3f263',
    messagingSenderId: '111924293210',
    projectId: 'smartbar-4700',
    storageBucket: 'smartbar-4700.firebasestorage.app',
    iosBundleId: 'com.example.barStockappCodexai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_ooudAP-7AnSEoQLLTupnN_up9fnGXM',
    appId: '1:111924293210:ios:c7ed8cc55135eef8d3f263',
    messagingSenderId: '111924293210',
    projectId: 'smartbar-4700',
    storageBucket: 'smartbar-4700.firebasestorage.app',
    iosBundleId: 'com.example.barStockappCodexai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnhJvbzYCu0VxUqSG8hhf6oRITqTpRms4',
    appId: '1:111924293210:web:9135d57fa525827fd3f263',
    messagingSenderId: '111924293210',
    projectId: 'smartbar-4700',
    authDomain: 'smartbar-4700.firebaseapp.com',
    storageBucket: 'smartbar-4700.firebasestorage.app',
    measurementId: 'G-LYYYMQVR2R',
  );
}
